app/login/__init__.py
from flask import Blueprint

login_bp = Blueprint('login', __name__)

from . import views

app/login/views.py
from flask import current_app, flash, redirect, render_template, url_for, request, abort, make_response

from ..controllers.user import UserController
from ..exceptions import UserRegistrationInvalidDataError, UserBlockedError
from ..auth import login as auth_login, logout as auth_logout, is_authenticated
from . import login_bp

@login_bp.route('/register', methods=['GET', 'POST'])
def register():
    if is_authenticated():
        return redirect(url_for('bouncer.home'))

    registration_enabled = current_app.config.get('REGISTRATION_ENABLED', False)
    if not registration_enabled:
        flash('Registration is disabled.', 'warning')
        return redirect(url_for('bouncer.home'))

    errors = None
    if request.method == 'POST':
        try:
            UserController.check_user_data( \
                name=request.form['name'], \
                email=request.form['email'], \
                password=request.form['password'], \
                password2=request.form['password2'])
            UserController.create( \
                name=request.form['name'], \
                email=request.form['email'], \
                password=request.form['password'])
            
            return make_response(render_template('login/register_success.html', title='Registration'))

        except UserRegistrationInvalidDataError as e:
            errors = e.errors
            flash('Some fields have errors: ' + ', '.join(errors), 'error')
    return make_response(render_template('login/register.html', title='Registration', errors=errors))


@login_bp.route('/confirm/email')
def confirm_email():
    email = request.args.get('email')
    token = request.args.get('token')
    action = request.args.get('action')
    if action == 'confirm':
        if not UserController.confirm_email(email, token):
            abort(404)
        return make_response(render_template('login/confirm_email_confirmed.html', title='Email Address confirmed'))
    elif not UserController.verify_confirm_email(email, token):
        abort(404)

    return make_response(render_template('login/confirm_email.html', title='Confirm Email Address', email=email, token=token))


@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    if is_authenticated():
        return redirect(url_for('bouncer.home'))

    if request.method == 'POST':
        try:
            auth_login(request.form['email'], request.form['password'])
            return redirect(url_for('bouncer.home'))
        except UserBlockedError:
            flash('Account has been blocked. Please contact an administrator.', 'error')
        except:
            flash('Invalid Credentials. Please try again.', 'error')
    return make_response(render_template('login/login.html', title='Login'))


@login_bp.route('/password/forgotten', methods=['GET', 'POST'])
def password_forgotten():
    if is_authenticated():
        return redirect(url_for('bouncer.home'))

    errors = None
    if request.method == 'POST':
        user = UserController.get_by_email(request.form['email'])
        if user:
            UserController.send_password_reset_email(user)
        flash('Instructions on how to reset the password has been sent the your email inbox.')
        return redirect(url_for('login.login'))

    return make_response(render_template('login/password_forgotten.html', title='Forgotten Password'))


@login_bp.route('/password/reset', methods=['GET', 'POST'])
def password_reset():
    email = request.args.get('email')
    token = request.args.get('token')

    if not UserController.verify_confirm_email(email, token):
        abort(404)

    if request.method == 'POST':
        if request.form['password'] is not None and \
            len(request.form['password']) > 0 and \
                request.form['password'] == request.form['password2']:
            if UserController.reset_password(email, token, request.form['password']):
                flash('Password has been reset! Please try to log in with the new password.')
                return redirect(url_for('login.login'))
            else:
                flash('Could not reset password. An unknown error has occured.', 'error')
        else:
            flash('Passwords do not match.', 'error')
    return make_response(render_template('login/password_reset.html', title='Password Reset'))


@login_bp.route('/password/set', methods=['GET', 'POST'])
def password_set():
    email = request.args.get('email')
    token = request.args.get('token')

    if not UserController.verify_confirm_email(email, token):
        abort(404)

    if request.method == 'POST':
        if request.form['password'] is not None and \
            len(request.form['password']) > 0 and \
                request.form['password'] == request.form['password2']:
            if UserController.reset_password(email, token, request.form['password'], confirm_email=True):
                flash('Password has been reset! Please try to log in with the new password.')
                return redirect(url_for('login.login'))
            else:
                flash('Could not reset password. An unknown error has occured.', 'error')
        else:
            flash('Passwords do not match.', 'error')
    return make_response(render_template('login/password_reset.html', title='Password Reset'))



@login_bp.route('/logout')
def logout():
    if auth_logout():
        return make_response(render_template('login/logout.html', title='Logout'))
    return redirect(url_for('bouncer.home'))

app/templates/login/confirm_email.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Confirm Email Address</h2>
    <br>
    <p>Do you want to confirm your email address {{ email }}?</p>
    <p>
      <form action="" method="get">
        <input type="hidden" name="email" value="{{ email }}">
        <input type="hidden" name="token" value="{{ token }}">
        <input type="hidden" name="action" value="confirm">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input class="btn btn-primary" type="submit" value="Confirm">
        <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Abort</a>
      </form>
      
    </p>
  </div>
</div>
{% endblock %}

app/templates/login/confirm_email_confirmed.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Email address confirmed!</h2>
    <br>
    <p>Your email address is now confirmed. Sign in to use your new account.</p>
    <p>
      <a class="btn btn-default" role="button" href="{{ url_for('login.login') }}">Login</a>
      <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Home</a>
    </p>
  </div>
</div>
{% endblock %}

app/templates/login/login.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Log in to your personal Account</h2>
    <br>
    <form action="" method="post">
      <label for="email">Email:</label><br>
      <input type="email" id="email" name="email" value="{{ request.form.email }}"><br/>
      <label for="name">Password:</label><br>
      <input type="password" id="password" name="password" value="{{ request.form.password }}"><br/>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input class="btn btn-primary" type="submit" value="Login"> or 
      <a class="btn btn-default" role="button" href="{{ url_for('login.password_forgotten') }}">Password forgotten?</a> or 
      <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Go back</a>
    </form>
  </div>
</div>
{% endblock %}

app/templates/login/logout.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <p>You have successfully been logged out.</p>
    <br/>
    <a class="btn btn-default" role="button" href="{{ url_for('login.login') }}">Login</a>
     or 
    <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Home</a>
  </div>
</div>
{% endblock %}

app/templates/login/password_forgotten.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Password forgotten?</h2>
    <br>
    <p>Request instructions for resetting the password.</p>
    <form action="" method="post">
      <label for="email">Email:</label><br>
      <input type="email" id="email" name="email" value="{{ request.form.email }}"><br/>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input class="btn btn-primary" type="submit" value="Request password reset"> or 
      <a class="btn btn-default" role="button" href="{{ url_for('login.login') }}">Go back</a>
    </form>
  </div>
</div>
{% endblock %}

app/templates/login/password_reset.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Set a new Password</h2>
    <br>
    <p>Set a new password for {{ email }}.</p>
    <form action="" method="post">
      <label for="name">New Password:</label><br>
      <input type="password" id="password" name="password" value="{{ request.form.password }}"><br/>
      <label for="name">Repeat new Password:</label><br>
      <input type="password" id="password2" name="password2" value="{{ request.form.password2 }}"><br/>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input class="btn btn-primary" type="submit" value="Set new Password"> or 
      <a class="btn btn-default" role="button" href="{{ url_for('login.login') }}">Go back</a>
    </form>
  </div>
</div>
{% endblock %}

app/templates/login/register.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Register a new Account</h2>
    <br>
    <form action="" method="post">
      <label for="name">Name:</label><br>
      <input type="text" id="name" name="name" value="{{ request.form.name }}"><br/>
      <label for="email">Email:</label><br>
      <input type="text" id="email" name="email" value="{{ request.form.email }}"><br/>
      <label for="name">Password:</label><br>
      <input type="password" id="password" name="password" value="{{ request.form.password }}"><br/>
      <label for="name">Repeat Password:</label><br>
      <input type="password" id="password2" name="password2" value="{{ request.form.password2 }}"><br/>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input class="btn btn-primary" type="submit" value="Register"> or 
      <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Go back</a>
    </form>
  </div>
</div>
{% endblock %}

app/templates/login/register_success.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>Bastli Bouncer</h1>
    <br/>
    <h2>Registration successful!</h2>
    <br>
    <p>Please check the inbox of your email address and follow the instructions.</p>
    <p>
      <a class="btn btn-default" role="button" href="{{ url_for('login.login') }}">Login</a>
      <a class="btn btn-default" role="button" href="{{ url_for('bouncer.home') }}">Home</a>
    </p>
  </div>
</div>
{% endblock %}